package BrazilCenter.transfer.tasks;

/***
 * Taks type, new file or failed file, 
 * NewTask: It's the first time we deal with it;
 * LocalFailedTask: the error records that stored in errRecords directory.
 * RemoteTask: the task that generated by the reupload service. 
 * @author Fuli Ma
 *
 */
public enum TASKTYPE {
	NewTask,	//new tasks 
	SubFailedTask, // one of the transfer threads failed to transfer the file.
	LocalFailedTask,  // tasks generated acccording to the records in errRecords directory.
	RemoteTask // tasks generate by reupload service. 
}
